### ISSUE TITLE
Versioning for operators

### ISSUE THREAD

**Issue by jjmachan** [bentoml/bentoctl#132]
- version:
    - use github tag
        
```python
[operator.name] = {
            "path": os.path.abspath(operator.path),
            "git_url": git_url,
            "git_branch": git_branch,
            "is_local": is_local,
      "version": GIT_TAG,
        }
```
        

```python
bentoctl operator update aws-lambda -> update to the latest tag
bentoctl operator update aws-lambda --pre -> update to the latest commit on main
```

**Comment by yubozhao** [comment]
Update on this proposal:
Update CLI commands, with `--version` option.

```bash
bentoctl operator install aws-lambda --version 0.1.0
bentoctl operator update aws-lambda --version 0.2.0
```

Update the operator list json to new format:
```
{
     "operator.name": {
            "path": operator.path,
            "git_url": git_url,
            "git_branch": git_branch,
            "is_local": is_local,
           "version": GIT_TAG,  // new addition
        }
}
```

Update deployment config.yaml with additional operator version 
```yaml
api_version: v1
name: quickstart
operator: aws-lambda
operator:
     name: aws-lambda
    version: OPTIONAL, if not provided will use the latest version from git repo
    url: OPTIONAL
template: terraform
spec:
    region: us-west-1
    timeout: 10
    memory_size: 512
```

Also, include version information in tracking.
